//
//  Flags.swift
//  Questionnaire
//
//  Created by Marat Shagiakhmetov on 10.04.2023.
//

import Foundation

class Flags {
    static let shared = Flags()
    
    let images = ["australia", "austria", "azerbaijan", "aland islands", "albania",
    "algeria", "american samoa", "anguilla", "angola", "andorra", "antarctica",
    "antigua and barbuda", "argentina", "armenia", "aruba", "british isles",
    "afghanistan", "bahamas", "bangladesh", "barbados", "bahrain", "belarus",
    "belize", "belgium", "benin", "bermuda", "bulgaria", "bolivia", "bonaire",
    "bosnia and herzegovina", "bostwana", "brazil", "brunei", "burkina-faso",
    "burundi", "bhutan", "vanuatu", "vatican city", "great britain", "hungary",
    "venezuela", "british virgin islands", "united states virgin islands",
    "east timor", "vietnam", "gabon", "haiti", "guyana", "gambia", "ghana",
    "guadepoule", "guatemala", "guinea", "guinea-bissau", "germany", "guernsey",
    "gibraltar", "honduras", "hong kong", "grenada", "greenland", "greece",
    "georgia", "guam", "denmark", "jersey", "djibouti", "dominica",
    "dominican republic", "egypt", "zambia", "western sahara", "zimbabwe",
    "israel", "india", "indonesia", "jordan", "iraq", "iran", "ireland", "iceland",
    "spain", "italy", "yemen", "cabo-verde", "kazakhstan", "cambodia", "cameroon",
    "canada", "qatar", "kenya", "cyprus", "kyrgyzstan", "kiribati", "china",
    "north korea", "cocos islands", "colombia", "comoros", "republic congo",
    "democratic republic of the congo", "kosovo", "costa rica", "ivory coast",
    "cuba", "kuwait", "curacao", "laos", "latvian", "lesotho", "liberia", "lebanon",
    "libya", "lithuania", "liechtenstein", "luxembourg", "mauritius", "mauritania",
    "madagascar", "mayotte", "makau", "malawi", "malaysia", "mali", "maldives",
    "malta", "morocco", "martinique", "marshall islands", "mexico", "micronesia",
    "mozambique", "moldova", "monaco", "mongolia", "montserrat", "myanmar",
    "namibia", "nauru", "nepal", "niger", "nigeria", "netherlands", "nicaragua",
    "niue", "new zealand", "new caledonia", "norway", "isle of man", "norfolk island",
    "christmas islands", "saint helena islands", "pitcairn islands",
    "turks and caicos islands", "uae", "oman", "cayman islands", "cook islands",
    "pakistan", "palau", "palestine", "panama", "papua new guinea", "paraguay",
    "peru", "poland", "portugal", "puerto rico", "south korea", "reunion",
    "russia", "rwanda", "romania", "el salvador", "samoa", "san marino",
    "sao tome and principe", "saudi arabia", "northern macedonia",
    "northern mariana islands", "seychelles islands", "saint-barthelemy",
    "saint-pierre and miquelon", "senegal", "saint vincent and grenadines",
    "saint kitts and nevis", "saint lucia", "serbia", "singapore", "sint maarten",
    "syria", "slovakia", "slovenia", "usa", "solomon islands", "somalia",
    "sudan", "suriname", "sierra leone", "tajikistan", "thailand", "taiwan",
    "tanzania", "togo", "tokelau", "tonga", "trinidad and tobago", "tuvalu",
    "tunisia", "turkmenistan", "turkey", "uganda", "uzbekistan", "ukraine",
    "wallis and futuna", "uruguay", "faroe islands", "fiji", "philippines",
    "finland", "falkland islands", "france", "french guiana", "french polynesia",
    "eparse islands", "croatia", "central african republic", "chad", "montenegro",
    "czech", "chile", "switzerland", "sweden", "sri lanka", "ecuador",
    "equatorial guinea", "eritrea", "eswatini", "estonia", "ethiopia",
    "south georgia and south sandwich", "south africa", "south sudan", "jamaica",
    "japan"]
    
    let names = ["Австралия", "Австрия", "Азербайджан", "Аландские острова",
    "Албания", "Алжир", "Американское Самоа", "Ангилья", "Ангола", "Андорра",
    "Антарктида", "Антигуа и Барбуда", "Аргентина", "Армения", "Аруба",
    "Британские острова", "Афганистан", "Багамские острова", "Бангладеш",
    "Барбадос", "Бахрейн", "Белорусь", "Белиз", "Бельгия", "Бенин",
    "Бермудские острова", "Болгария", "Боливия", "Бонэйр", "Босния и Герцеговина",
    "Ботсвана", "Бразилия", "Бруней", "Буркина-Фасо", "Бурунди", "Бутан",
    "Вануату", "Ватикан", "Великобритания", "Венгрия", "Венесуэла",
    "Британские Виргинские острова", "Американские Виргинские острова",
    "Восточный Тимор", "Вьетнам", "Габон", "Гаити", "Гайана", "Гамбия", "Гана",
    "Гваделупа", "Гватемала", "Гвинея", "Гвинея-Бисау", "Германия", "Гернси",
    "Гибралтар", "Гондурас", "Гонконг", "Гренада", "Гренландия", "Греция",
    "Грузия", "Гуам", "Дания", "Джерси", "Джибути", "Доминика",
    "Доминиканская республика", "Египет", "Замбия", "Западная Сахара",
    "Зимбабве", "Израиль", "Индия", "Индонезия", "Иордания", "Ирак", "Иран",
    "Ирландия", "Исландия", "Испания", "Италия", "Йемен", "Кабо-Верде",
    "Казахстан", "Камбоджа", "Камерун", "Канада", "Катар", "Кения", "Кипр",
    "Киргизия", "Кирибати", "Китай", "КНДР", "Кокосовые острова", "Колумбия",
    "Коморские острова", "Республика Конго", "Демократическая Республика Конго",
    "Косово", "Коста-Рика", "Кот-д'Ивуар", "Куба", "Кувейт", "Кюрасао", "Лаос",
    "Латвия", "Лесото", "Либерия", "Ливан", "Ливия", "Литва", "Лихтенштейн",
    "Люксембург", "Маврикий", "Мавритания", "Мадагаскар", "Майотта", "Макао",
    "Малави", "Малайзия", "Мали", "Мальдивские острова", "Мальта", "Марокко",
    "Мартиника", "Маршалловы острова", "Мексика", "Микронезия", "Мозамбик",
    "Молдова", "Монако", "Монголия", "Монтсеррат", "Мьянма", "Намибия", "Науру",
    "Непал", "Нигер", "Нигерия", "Нидерланды", "Никарагуа", "Ниуэ",
    "Новая Зеландия", "Новая Каледония", "Норвегия", "Остров Мэн", "Остров Норфолк",
    "Остров Роджества", "Острова Святой Елены", "Острова Питкэрн",
    "Острова Теркс и Кайкос", "ОАЭ", "Оман", "Каймановы острова", "Острова Кука",
    "Пакистан", "Палау", "Палестина", "Панама", "Папуа - Новая Гвинея", "Парагвай",
    "Перу", "Польша", "Португалия", "Пуэрто-Рико", "Южная Корея", "Реюньон",
    "Россия", "Руанда", "Румыния", "Сальвадор", "Самоа", "Сан-Марино",
    "Сан-Томе и Принсипи", "Саудовская Аравия", "Северная Македония",
    "Северные Марианские острова", "Сейшельские острова", "Сен-Бартелеми",
    "Сен-Пьер и Микелон", "Сенегал", "Сент-Винсент и Гренадины",
    "Сент-Китс и Невис", "Сент-Люсия", "Сербия", "Сингапур", "Синт-Мартен",
    "Сирия", "Словакия", "Словения", "США", "Соломоновы острова", "Сомали",
    "Судан", "Суринам", "Сьерра-Леоне", "Таджикистан", "Таиланд", "Тайвань",
    "Танзания", "Того", "Токелау", "Тонга", "Тринидад и Тобаго", "Тувалу", "Тунис",
    "Туркменистан", "Турция", "Уганда", "Узбекистан", "Украина", "Уоллис и Футуна",
    "Уругвай", "Фарерские острова", "Фиджи", "Филиппины", "Финляндия",
    "Фолклендские острова", "Франция", "Французская Гвиана", "Французская Полинезия",
    "Острова Эпарс", "Хорватия", "Центральноафриканская Республика",
    "Чад", "Черногория", "Чехия", "Чили", "Швейцария", "Швеция", "Шри-Ланка",
    "Эквадор", "Экваториальная Гвинея", "Эритрея", "Эсватини", "Эстония",
    "Эфиопия", "Южная Георгия и Южные Сандвичевы", "ЮАР", "Южный Судан", "Ямайка",
    "Япония"]
}
